# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: poe-format
        name: Format
        entry: poe format
        pass_filenames: false
        language: python
      - id: poe-lint
        name: Lint
        entry: poe lint
        pass_filenames: false
        verbose: true
        language: python
