[tool.poetry]
name = "flask-quickstart"
version = "0.1.0"
description = "My first app by Flask."
authors = ["Noritaka IZUMI <noritaka.izumi@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "flask_quickstart"}]

[tool.poetry.dependencies]
python = "^3.8"
flask = "^2.3.2"
python-dotenv = "^1.0.0"
gevent = "^23.7.0"


[tool.poetry.group.dev.dependencies]
watchdog = "^3.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
