name: E2E Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    uses: ./.github/workflows/python-venv.yml
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      # setup python
      - name: Load python venv
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ needs.build.outputs.cache-key }}
      - name: Activate python venv
        run: |
          . ./.venv/bin/activate
          echo "PATH=$PATH" >> "$GITHUB_ENV"
      # setup node.js
      - uses: actions/setup-node@v3
        id: setup-node
        with:
          node-version: 18
          cache: npm
      - name: Load node modules
        id: load-node-modules
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: node_modules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: ${{ steps.setup-node.outputs.cache-hit != 'true' }}
        run: npm ci
      - name: Export Playwright browsers path
        run: echo "PLAYWRIGHT_BROWSERS_PATH=$HOME/pw-browsers" >> "$GITHUB_ENV"
      # setup playwright browsers
      # caching browser binaries is not recommended: https://playwright.dev/docs/ci#caching-browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      # run tests
      - name: Run E2E tests
        run: npm run test:e2e
      # report
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
