name: E2E Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  NODE_VERSION: 18
jobs:
  build-python:
    uses: ./.github/workflows/python-venv.yml
  build-node-modules:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - id: node-modules-cache-key
        run: echo "value=node_modules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}" >> "$GITHUB_OUTPUT"
      - uses: actions/setup-node@v3
        id: setup-node
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - name: Load node modules
        id: load-node-modules
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ steps.node-modules-cache-key.outputs.value }}
      - name: Install dependencies
        if: ${{ steps.setup-node.outputs.cache-hit != 'true' }}
        run: npm ci
    outputs:
      cache-key: ${{ steps.node-modules-cache-key.outputs.value }}
  lint:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        id: setup-node
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - name: Load node modules
        id: load-node-modules
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ needs.build-node-modules.outputs.value }}
      - name: Run lint
        run: |
          npm run prettier
          npm run eslint
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    needs:
      - build-python
      - build-node-modules
    steps:
      - uses: actions/checkout@v3
      # setup python
      - name: Load python venv
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ needs.build.outputs.cache-key }}
      - name: Activate python venv
        run: |
          . ./.venv/bin/activate
          echo "PATH=$PATH" >> "$GITHUB_ENV"
      # setup node.js
      - uses: actions/setup-node@v3
        id: setup-node
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - name: Load node modules
        id: load-node-modules
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ needs.build-node-modules.outputs.value }}
      # setup playwright browsers
      # caching browser binaries is not recommended: https://playwright.dev/docs/ci#caching-browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      # run tests
      - name: Run E2E tests
        run: npm run test:e2e
      # report
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
