name: E2E Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    uses: ./.github/workflows/python-venv.yml
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      - name: Load python venv
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ needs.build.outputs.cache-key }}
      - name: Activate python venv
        run: |
          . ./.venv/bin/activate
          echo "PATH=$PATH" >> "$GITHUB_ENV"
      - uses: actions/setup-node@v3
        id: setup-node
        with:
          node-version: 18
          cache: npm
      - name: Install dependencies
        if: ${{ steps.setup-node.outputs.cache-hit != 'true' }}
        run: npm ci
      - name: Export Playwright browsers path
        run: echo "PLAYWRIGHT_BROWSERS_PATH=$HOME/pw-browsers" >> "$GITHUB_ENV"
      - name: Load Playwright browsers
        id: load-playwright-browsers
        uses: actions/cache@v3
        with:
          path: ${{ env.PLAYWRIGHT_BROWSERS_PATH }}
          key: playwright_browsers-${{ runner.os }}-${{ hashFiles('e2e/**/*.spec.ts') }}
      - name: Install Playwright Browsers
        if: ${{ steps.load-playwright-browsers.outputs.cache-hit != 'true' }}
        run: npx playwright install --with-deps
      - name: Run E2E tests
        run: npm run test:e2e
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
