name: Playwright Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    uses: ./.github/workflows/python-venv.yml
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      - name: Load python venv
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ needs.build.outputs.cache-key }}
      - name: Activate python venv
        run: |
          . ./.venv/bin/activate
          echo "PATH=$PATH" >> "$GITHUB_ENV"
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Load node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Export Playwright browsers path
        run: echo "PLAYWRIGHT_BROWSERS_PATH=$HOME/pw-browsers" >> "$GITHUB_ENV"
      - name: Load Playwright browsers
        uses: actions/cache@v3
        with:
          path: ${{ env.PLAYWRIGHT_BROWSERS_PATH }}
          key: playwright_browsers-${{ runner.os }}-${{ hashFiles('e2e/**/*.spec.ts') }}
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
