name: Pytest
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    uses: ./.github/workflows/python-venv.yml
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      # setup python
      - name: Load python venv
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ needs.build.outputs.cache-key }}
      - name: Activate python venv
        run: |
          . ./.venv/bin/activate
          echo "PATH=$PATH" >> "$GITHUB_ENV"
      # run tests
      - uses: actions/cache@v3
        id: pytest-cache
        with:
          path: '**/.pytest_cache'
          key: pytest_cache-${{ runner.os }}-${{ hashFiles('tests/**/*.py') }}
      - name: Run pytest
        run: poe test
